package com.jbk.entity;

// default package
// Generated Mar 6, 2021 5:06:56 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "test")
public class Country implements java.io.Serializable {

	private int cid;
	private String city;
	private Set persons = new HashSet(0);

	public Country() {
	}

	public Country(int cid) {
		this.cid = cid;
	}

	public Country(int cid, String city, Set persons) {
		this.cid = cid;
		this.city = city;
		this.persons = persons;
	}

	@Id

	@Column(name = "cid", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

}
