package com.jbk.entity;
// Generated Mar 6, 2021 5:06:56 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "test")
public class Events implements java.io.Serializable {

	private Integer id;
	private String eventName;
	private Date eventDate;
	private String eventMonth;
	private String eventLocation;

	public Events() {
	}

	public Events(String eventName, Date eventDate, String eventMonth, String eventLocation) {
		this.eventName = eventName;
		this.eventDate = eventDate;
		this.eventMonth = eventMonth;
		this.eventLocation = eventLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "event_name", nullable = false, length = 45)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "event_date", nullable = false, length = 19)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@Column(name = "event_month", nullable = false, length = 45)
	public String getEventMonth() {
		return this.eventMonth;
	}

	public void setEventMonth(String eventMonth) {
		this.eventMonth = eventMonth;
	}

	@Column(name = "event_location", nullable = false, length = 45)
	public String getEventLocation() {
		return this.eventLocation;
	}

	public void setEventLocation(String eventLocation) {
		this.eventLocation = eventLocation;
	}

}
